project:
  name: ecommerce-lakehouse
  catalog: ecommerce

storage:
  container: "<adls-container-name>"
  storage_account: "<storage-account-name>"
  root_path: "ecommerce-catalog"

paths:
  raw: "abfss://<container>@<storage>.dfs.core.windows.net/ecommerce-catalog/raw"
  bronze: "abfss://<container>@<storage>.dfs.core.windows.net/ecommerce-catalog/bronze"
  silver: "abfss://<container>@<storage>.dfs.core.windows.net/ecommerce-catalog/silver"
  gold: "abfss://<container>@<storage>.dfs.core.windows.net/ecommerce-catalog/gold"

secrets:
  scope: "ecommerce-scope"
  adls_key_name: "adls-key"

tables:
  bronze:
    brands: "brz_brands"
    calendar: "brz_calendar"
    category: "brz_category"
    customers: "brz_customers"
    order_items: "brz_order_items"
    order_returns: "brz_order_returns"
    order_shipments: "brz_order_shipments"
    products: "brz_products"

  silver:
    brands: "slv_brands"
    calendar: "slv_calendar"
    category: "slv_category"
    customers: "slv_customers"
    order_items: "slv_order_items"
    order_returns: "slv_order_returns"
    order_shipments: "slv_order_shipments"
    products: "slv_products"

  gold:
    dim_customers: "gld_dim_customers"
    dim_products: "gld_dim_products"
    dim_date: "gld_dim_date"
    fact_order_items: "gld_fact_order_items"
    fact_order_returns: "gld_fact_order_returns"
    fact_order_shipments: "gld_fact_order_shipments"
    fact_daily_summary: "gld_fact_daily_orders_summary"
